### ISSUE TITLE
CSS渐变专题

### ISSUE THREAD

**Issue by smileyby** [smileyby/notes#101]
任务说明：
1.理清楚 linear-gradient和radial-gradient用法
2.总结两种渐变在实际应用中的使用场景，并附带效果代码和展示图
![效果图](https://s2.ax1x.com/2020/01/29/1QgiwT.png)

**Comment by smileyby** [comment]
## linear-gradient

> **概念**：CSS `linear-gradient()`用于创建一个表示两种或多种颜色线性渐变的图片。其结果属于<gradient>数据类型，是一种特别的<image>数据类（所以可以给其设置`background-size`属性）

> **语法**：
>
> * `<side-or-corner>`：描述渐变线的起始点位置。它包含to和两个关键词：第一个置出水平位置left or right，第二个置出垂直位置top or bottom。关键词的先后顺序无影响，且都是可选的；to top，to bottom，to left 和 to right这些值会被转换为角度0度、180度、270度和90度。其余值会被转换为一个以向顶部中央为起点顺时针旋转的角度。剑便向的结束点和其起点中心对称
> * `<angle>`：用角度值指定渐变的方向（或角度）。角度顺时针增加
> * `<linear-color-stop>`：由一个[<color>](https://developer.mozilla.org/zh-CN/docs/Web/CSS/color_value)值组成，并且跟随者一个可选的终点值（可以是一个百分比或者是沿着渐变轴的[<length>](https://developer.mozilla.org/zh-CN/docs/Web/CSS/length)）。CSS渐变的颜色渲染采取了与svg相同的规则
> * `<color-hint>`：颜色中转点是一个插值提示，它定义了在相邻颜色之间渐变如何进行。长度定义了在两种颜色之间的那个点停止渐变颜色应该达到颜色过度的中点，如果省略，颜色转换的中点是两个颜色停止之间的中点。
> * **真是语法**：`linear-gradient([<angle> | to <side-or-corner>, ]?<color-stop-list>)`

> **兼容性**：
>
> ![linear-gradient兼容性](https://s2.ax1x.com/2020/01/29/1QfW24.md.png)

```css
body {
	margin: 0;
}
.container {
	height: 200px;
	background: linear-gradient(yellow, green); /* 不写方向，默认从上到下 */
	background: linear-gradient(to left, yellow, green); /* 黄色 从右向左渐变成 绿色 */
	background: linear-gradient(to bottom, yellow, green); /* 黄色 从上到下渐变成 绿色 */
	background: linear-gradient(to right top, yellow, green); /* 黄色 从左下到右上渐变成 绿色 */
	background: linear-gradient(20deg, yellow, green); /* 顺时针20度 黄色 从左下到右上渐变成绿色 */
	background: linear-gradient(yellow, green, pink, red); /* 从上向下 颜色依次渐变，且渐变区域等分容器高度 */
	background: linear-gradient(yellow 0%, green 20%, red 100%); /* 可以百分比指定渐变的区域结束位置 */
	background: linear-gradient(yellow 0, green 150px 160px, red 200px, yellow); /* 也可以使用px来指定渐变区域的结束为止 */
	background: linear-gradient(45deg, transparent 0, transparent 49.5%, yellow 50%, transparent 50.5%, transparent 100%),
	            linear-gradient(135deg, transparent 0, transparent 49.5%, green 50%, transparent 50.5%, transparent 100%); /* 线性渐变实现网格效果 */
	background-size: 30px 30px;
	box-shadow: inset 1px 1px 5px black;
}

.imgBox {
	height: 200px;
	overflow: hidden;
	border: 1px dashed #ff6700;
	position: relative;
	cursor: pointer;
}
.imgBox img {
	width: 100%;
	height: 100%;
}
.bg {
	position: absolute;
	left: -100%;
	top: 0;
	width: 100%;
	height: 100%;
	background: linear-gradient(135deg, rgba(255,255,255,0), rgba(255,255,255,0.5), rgba(255,255,255,0));
	transition: 0.5s; 
}
.imgBox:hover .bg {
	left: 100%;
}
```

```html
<div class="container"></div>
<div class="imgBox">
	<img id="img" src="https://s2.ax1x.com/2020/01/21/1FqssK.png" alt="">
	<label for="img" class="bg"></label>
</div>
```
