### ISSUE TITLE
各大网站实现灰度的方法

### ISSUE THREAD

**Issue by smileyby** [smileyby/notes#109]
1. grayscale 灰度处理
```css
html {
  -webkit-filter: grayscale(100%);
  -moz-filter: grayscale(100%);
  -ms-filter: grayscale(100%);
  -o-filter: grayscale(100%);
  filter: grayscale(100%); 
  filter: gray;
  filter: url(data:image/svg+xml;utf8,#grayscale); /* 腾讯 */
  filter: progid:DXImageTransform.Microsoft.BasicImage(grayscale=1);  /* 抖音、淘宝、京东、美团、网易、去哪儿、滴滴 */
}
```
