### ISSUE TITLE
CSS：IOS系统下，一行代码实现简体和繁体切换

### ISSUE THREAD

**Issue by smileyby** [smileyby/notes#131]
> 需要字体本身支持 简体和繁体才可
```css
body {
    font-variant-east-asian: traditional;
}
```

参考：[一行CSS实现全站中文简繁转换](https://www.zhangxinxu.com/wordpress/2021/01/css-simplified-traditional-chinese/)
