### ISSUE TITLE
有个又去的css效果

### ISSUE THREAD

**Issue by smileyby** [smileyby/notes#134]
![面试题](https://user-images.githubusercontent.com/16968442/85370422-46a69980-b561-11ea-8113-2c3ebe6a0ff3.png)

```css
#ball {
  width: 0;
  height: 0;
  border: 100px solid #333;
  border-radius: 50%;
  border-top-left-color: transparent;
  border-bottom-right-color: transparent;
  transform: rotate(45deg);
}
```
