### ISSUE TITLE
图片加载失败兜底方案实现--转自张鑫旭博客

### ISSUE THREAD

**Issue by smileyby** [smileyby/notes#158]
```html
<img src="street.jpg" alt="街道">
<img src="zxx.jpg" alt="CSS新世界封面" onerror="this.classList.add('error');">
<img src="moon-night.jpg" alt="夜景星空">
```

```css
img.error {
  display: inline-block;
  transform: scale(1);
  content: '';
  color: transparent;
}
img.error::before {
  content: '';
  position: absolute;
  left: 0; top: 0;
  width: 100%; height: 100%;
  background: #f5f5f5 url(break.svg) no-repeat center / 50% 50%;
}
img.error::after {
  content: attr(alt);
  position: absolute;
  left: 0; bottom: 0;
  width: 100%;
  line-height: 2;
  background-color: rgba(0,0,0,.5);
  color: white;
  font-size: 12px;
  text-align: center;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
```

参考链接：https://www.zhangxinxu.com/study/202010/image-error-show-alt-demo.php
