### ISSUE TITLE
text-align: justify

### ISSUE THREAD

**Issue by smileyby** [smileyby/notes#199]
```css
.text {
  text-align: justify;
}
.text:after {
 display: inline-block;
 width: 100%;
 content: "";
}
```
仅针对文字 非最后一行生效，所以开发中要对最后一行生效需要借助 伪类
