### ISSUE TITLE
小程序内部使用定位，在ios中可能会导致横向滚动

### ISSUE THREAD

**Issue by smileyby** [smileyby/notes#80]
```css
.btn {
 position: absolute;
 left: 999px;
 top: 999px;
}
```
这样会导致，它占用着空间产生横向滚动条（IOS中）

**Comment by smileyby** [comment]
这里是为了隐藏元素，我设置按钮的位置为 左999 上999，导致在ios端打开页面的时候会出现横向滚动条。
上面代码做如下修改
```css
.btn {
  position: absolute;
  left: 0;
  top: 0;
  opacity: 0;
}
```
